version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Mohit@005
      MYSQL_DATABASE: wellflowsyncdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./MEDICAL_APPOINTMENT_SYSTEM_BACKEND
    container_name: spring-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wellflowsyncdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mohit@005
    ports:
      - "9096:8080"

  frontend:
    build: ./MEDICAL_APPOINTMENT_SYSTEM_FRONTEND
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "5173:8080"

volumes:
  mysql_data:
